### ISSUE TITLE
Mostrar mensajes de error en pantalla de login

### ISSUE THREAD

**Issue by GAumala** [GAumala/DAW#3]
Si pongo mal mis credenciales, al redirigirme a la misma pantalla debe de mostrar un mensaje de error.

Asi mismo si cierro sesion, se me redirige a la pantalla de login debe de haber un mensaje confirmando que cerre sesion,

**Comment by hjupiter** [comment]
ya muestra el error cuando no se ha logeado bien

**Comment by GAumala** [comment]
Excelente, ya lo puse en master.
